---
- name: Combine postgresql variables
  set_fact:
    postgresql: "{{ (postgresql | default({})) | combine(postgresql_defaults, recursive=True) }}"

- name: Install required utilities for becoming unprivileged user
  apt:
    name: acl
    state: present

- name: Ensure python3-psycopg2 is installed
  apt:
    name: python3-psycopg2
    state: present

- name: Install PostgreSQL
  apt:
    name: "postgresql-{{ postgresql.version }}"
    state: present

- name: Ensure PostgreSQL service is enabled and started
  service:
    name: postgresql
    state: started
    enabled: true

- block:
  - name: Bind to all addresses if launched in development mode
    set_fact:
      postgresql: "{{ postgresql | combine({'listen_addresses': '*'}, recursive=True) }}"

  - name: Allow remote connections for all users
    lineinfile:
      path: "/etc/postgresql/{{ postgresql.version }}/main/pg_hba.conf"
      insertafter: "^#.*TYPE.*DATABASE.*USER.*ADDRESS.*METHOD"
      line: "host    all             all    0.0.0.0/0    scram-sha-256"
    notify: Restart PostgreSQL

  - name: Change password for 'postgres' user
    become_user: postgres
    postgresql_user:
      name: postgres
      password: "{{ postgres_password }}"

  when: development_mode

- name: Configure PostgreSQL
  template:
    src: server.conf.j2
    dest: "/etc/postgresql/{{ postgresql.version }}/main/conf.d/01_server.conf"

- name: Ensure all configured locales are present.
  locale_gen: "name={{ item }} state=present"
  with_items: "{{ postgresql.locales }}"
  register: locale_gen_result

# We need to restart PostgreSQL to apply the new configuration before running the next tasks
- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted

# Needed by other roles to become the postgres user, for example, to create the databases
- name: Ensure /var/lib/postgresql/.ansible/tmp directory exists with correct permissions
  file:
    path: /var/lib/postgresql/.ansible/tmp
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
