---
- name: Bind to all addresses if launched in development mode
  set_fact:
    redis_bind_address: "0.0.0.0 ::1"
  when: running_environment == "development"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Redis
  apt:
    name: redis-server={{ redis_version }}
    state: present

- name: Ensure Redis is running
  systemd:
    name: redis-server
    state: started
    enabled: yes

- name: Copy Redis configuration file
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0640'
  notify: Restart Redis


