# Some task can't be executed in a dev environment, ie, certbot, and we will need
# some additional tasks (open ports, etc.)
development_mode: yes

server_timezone: "Europe/Madrid"

# Change if you have a non-standard ssh port
ssh_port: 22

registry:
  domain: "dev.registry.correctomatic.org"
  data_directory: "/var/registry"
  internal_port: 5000
  max_upload_size: 2G

docker:
  domain: "dev.docker.correctomatic.org"

correctomatic:
  # Shared folder between the API and the correctomatic processes
  shared_folder: /correctomatic/exercises

  # Shared network for the containers
  network: correctomatic

  docker_timeout: 10000

  api:
    image: correctomatic/api
    tag: latest
    log_level: debug

  runner:
    image: correctomatic/runner
    tag: latest
    # minutes
    delete_corrections_older_than: 3
    # Directory with the certs to be copied to the containers
    docker_certs_folder: /etc/docker

  starter:
    log_level: debug

  completer:
    log_level: debug

  notifier:
    log_level: debug

# correctomatic_app_domain: "correctomatic.alvaromaceda.es"
lets_encrypt_email: "alvaro@alvaromaceda.es"
