sudo_password: ansible

# The user is "default"
redis_password: "patata"

# Used for criptographic operations
registry_password: banana

# User used by the correctomatic processes to access the registry
correctomatic_registry_user: correctomatic
correctomatic_registry_password: correctomatic

# List of users that can access the docker registry
docker_registry_users:
  - { username: "{{ correctomatic_registry_user }}", password: "{{ correctomatic_registry_password }}" }
  - { username: user1, password: pass1 }
  - { username: user2, password: pass2 }
  - { username: user3, password: pass3 }

postgresql:
  # Password for the postgres user. Only used in development mode
  password: "postgres"
