---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Deploy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Ensure Nginx service is running
  service:
    name: nginx
    state: started
    enabled: true
