---
- name: Install apache2-utils if not present
  ansible.builtin.package:
    name: apache2-utils
    state: present

- name: Ensure the htpasswd file exists
  ansible.builtin.file:
    path: "{{ htpasswd_file }}"
    state: touch
    group: www-data
    mode: '0640'

- name: Include registry users if not already present
  include_tasks: add_registry_user.yml
  vars:
    username: "{{ item.username }}"
    password: "{{ item.password }}"
  loop: "{{ docker_registry_users }}"
