---
- name: Install apache2-utils if not present
  ansible.builtin.package:
    name: apache2-utils
    state: present

# MUST recreate the htpasswd file each time, because if not,
# old users will be here
- name: Remove existing htpasswd file
  ansible.builtin.file:
    path: "{{ htpasswd_file }}"
    state: absent

- name: Ensure the htpasswd file exists
  ansible.builtin.file:
    path: "{{ htpasswd_file }}"
    state: touch
    group: www-data
    mode: '0640'

- name: Add users to htpasswd file
  ansible.builtin.command:
    cmd: htpasswd -b "{{ htpasswd_file }}" "{{ item.username }}" "{{ item.password }}"
  loop: "{{ docker_registry_users }}"
  no_log: true
