---
- name: Check if private key exists
  stat:
    path: "/etc/ssl/{{ docker_registry_domain }}/privkey.pem"
  register: privkey_stat

- name: Check if certificate exists
  stat:
    path: "/etc/ssl/{{ docker_registry_domain }}/fullchain.pem"
  register: cert_stat

- name: Create directory for SSL certificates
  file:
    path: "/etc/ssl/{{ docker_registry_domain }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  when: not privkey_stat.stat.exists or not cert_stat.stat.exists

- name: Generate SSL private key
  openssl_privatekey:
    path: "/etc/ssl/{{ docker_registry_domain }}/privkey.pem"
    size: 4096
  when: not privkey_stat.stat.exists or not cert_stat.stat.exists

- name: Generate SSL certificate signing request (CSR)
  openssl_csr:
    path: "/etc/ssl/{{ docker_registry_domain }}/cert.csr"
    privatekey_path: "/etc/ssl/{{ docker_registry_domain }}/privkey.pem"
    common_name: "{{ docker_registry_domain }}"
    state: present
  when: not privkey_stat.stat.exists or not cert_stat.stat.exists

- name: Generate Self-Signed SSL certificate
  openssl_certificate:
    path: "/etc/ssl/{{ docker_registry_domain }}/fullchain.pem"
    privatekey_path: "/etc/ssl/{{ docker_registry_domain }}/privkey.pem"
    csr_path: "/etc/ssl/{{ docker_registry_domain }}/cert.csr"
    provider: selfsigned
    # 3650 => 10 years from now
    selfsigned_not_after: "{{ lookup('pipe', 'date -d ' ~ 3650 ~ 'days +%Y%m%d%H%M%SZ') }}"
    state: present
  when: not privkey_stat.stat.exists or not cert_stat.stat.exists
