---
- name: Setting up certificates
  debug:
    msg: "***** Setting up certificates for {{ domain }} *****"

- name: Ensure certificate directory exists for {{ domain }}
  file:
    path: "/etc/letsencrypt/live/{{ domain }}"
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Ensure domain-specific directory exists with 700 permissions
  file:
    path: "/etc/letsencrypt/live/{{ domain }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy fullchain.pem to the target directory
  copy:
    src: "{{ nginx[domain].cert_path  }}"
    dest: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
    owner: root
    group: root
    mode: '0644'
  when: nginx[domain].cert_path is defined

- name: Copy privkey.pem to the target directory
  copy:
    src: "{{ nginx[domain].key_path }}"
    dest: "/etc/letsencrypt/live/{{ domain }}/privkey.pem"
    owner: root
    group: root
    mode: '0600'
  when: nginx[domain].key_path is defined

- name: Check if the fullchain.pem file exists
  stat:
    path: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
  register: fullchain_file

- name: Check if the privkey.pem file exists
  stat:
    path: "/etc/letsencrypt/live/{{ domain }}/privkey.pem"
  register: privkey_file

- name: Include tasks to request certificates if they do not exist
  include_tasks: request_certificates.yml
  when: not (fullchain_file.stat.exists and privkey_file.stat.exists)
