---
- name: Install Certbot
  apt:
    name: certbot
    state: present
    update_cache: yes

- name: Install Certbot Nginx plugin
  apt:
    name: python3-certbot-nginx
    state: present

- name: Obtain SSL certificate from Let's Encrypt
  # command: >
  #   certbot certonly --non-interactive --agree-tos --email {{ lets_encrypt_email }}
  #   --standalone -d {{ registry.domain }}
  command: >
    certbot --nginx --non-interactive --agree-tos --email {{ lets_encrypt_email }}
    -d {{ registry.domain }}
  environment:
    PATH: "{{ ansible_env.PATH }}"
  args:
    creates: "/etc/letsencrypt/live/{{ registry.domain }}/fullchain.pem"

- name: Setup cron job for certbot renewals
  cron:
    name: "Renew Let's Encrypt certificates"
    job: "/usr/bin/certbot renew --quiet --renew-hook '/bin/systemctl reload nginx'"
    hour: 3
    minute: 0
