
---
- name: Print the value of docker_registry_domain
  debug:
    msg: "The value of docker_registry_domain is {{ docker_registry_domain }}"

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure Nginx for Docker registry
  template:
    src: nginx-docker-registry.conf.j2
    dest: /etc/nginx/sites-available/docker-registry
  notify: Reload Nginx

- name: Enable Nginx site configuration
  file:
    src: /etc/nginx/sites-available/docker-registry
    dest: /etc/nginx/sites-enabled/docker-registry
    state: link
  notify: Reload Nginx

# Debug
# - name: Remove default Nginx site
#   file:
#     path: /etc/nginx/sites-enabled/default
#     state: absent
#   notify: Reload Nginx
