---
# We need to check if the Nginx configuration file exists before creating it
# Because certbot modifies it, and will be rewritten if we launch the role again

- name: Configure Nginx for {{ name }} (Development)
  template:
    src: "{{ name }}.conf-dev.j2"
    dest: "/etc/nginx/sites-available/{{ name }}.conf"
  when: development_mode
  notify: Restart Nginx

- name: Configure Nginx for {{ name }} (Production)
  template:
    src: "{{ name }}.conf-prod.j2"
    dest: "/etc/nginx/sites-available/{{ name }}.conf"
  when: not development_mode
  notify: Restart Nginx

- name: Enable Nginx site configuration
  file:
    src: /etc/nginx/sites-available/{{ name }}.conf
    dest: /etc/nginx/sites-enabled/{{ name }}.conf
    state: link
  notify: Restart Nginx
