---
- name: Obtain SSL certificate from Let's Encrypt {{ domain }}
  command: >
    certbot --nginx --non-interactive --agree-tos --email {{ lets_encrypt_email }}
    -d {{ domain }}
  environment:
    PATH: "{{ ansible_env.PATH }}"
  args:
    creates: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
