ansible_become_pass: <sudo password for the ansible user>

# The user is "default"
redis_password: <password>

# Used for criptographic operations
registry_password: <password>

# User used by the correctomatic processes to access the registry
correctomatic_registry_user: <username>
correctomatic_registry_password: <password>

# List of users that can access the docker registry
docker_registry_users:
  - { username: "{{ correctomatic_registry_user }}", password: "{{ correctomatic_registry_password }}" }
  # Create more users as needed
  # - { username: user1, password: pass1 }
  # - { username: user2, password: pass2 }
  # - { username: user3, password: pass3 }
  # ...
