# Some task can't be executed in a dev environment, ie, certbot, and we will need
# some additional tasks (open ports, etc.)
development_mode: no

server_timezone: "Europe/Madrid"

# Change if you have a non-standard ssh port
ssh_port: 22

# In case you have the certificates, you can use them assigning the paths to the following variables
# For production mode only. In development, it uses self-signed certificates
# Paths are relative to nginx role, you can use {{ playbook_dir }} if you want to reference the playbook directory
# nginx:
#   app.correctomatic.org:
#     cert_path: "{{ playbook_dir }}/certs/app/fullchain1.pem"
#     key_path: "{{ playbook_dir }}/certs/app/privkey1.pem"
#   registry.correctomatic.org:
#     cert_path: "{{ playbook_dir }}/certs/registry/fullchain1.pem"
#     key_path: "{{ playbook_dir }}/certs/registry/privkey1.pem"

registry:
  domain: "registry.correctomatic.org"
  data_directory: "/var/registry"
  internal_port: 5000
  max_upload_size: 2G

docker:
  domain: "docker.correctomatic.org"

correctomatic:
  # Shared folder between the API and the correctomatic processes
  shared_folder: /correctomatic/exercises

  # Shared network for the containers
  network: correctomatic

  docker_timeout: 10000

  api:
    image: correctomatic/api
    tag: latest
    log_level: info

  runner:
    image: correctomatic/runner
    tag: latest
    # minutes
    delete_corrections_older_than: 3
    # Directory with the certs to be copied to the containers
    docker_certs_folder: /etc/docker

  starter:
    log_level: info

  completer:
    log_level: info

  notifier:
    log_level: info

  app:
    log_level: debug
    domain: "app.correctomatic.org"
    uploads_dir: "/correctomatic/app/uploads"

    network:
      name: app
      subnet: "172.20.0.0/16"

    internal_port: 8000
    max_upload_size: 10M
    db:
      name: "correctomatic"
      # Be sure that the locale is installed in the system, see roles/postgresql/tasks/main.yml
      encoding: "UTF8"
      lc_collate: "es_ES.UTF-8"
      lc_ctype: "es_ES.UTF-8"
    # TEMP
    repo: "https://github.com/correctomatic/correctomatic-app.git"
    branch: "master"

# You can configure postgresql here, see roles/ansible-role-postgresql/defaults/main.yml for valid options
postgresql:
  version: 16
  # The app network will be added to the listen_addresses
  # listen_addresses: "0.0.0.0"

# correctomatic_app_domain: "correctomatic.org"
lets_encrypt_email: "alvaro@alvaromaceda.es"
