---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - configuration/config.yml
    - secrets/sudo_password.yml
    - secrets/redis_password.yml

  tasks:
    - name: Print the environment configuration
      debug:
        msg: "Launching in mode: {{ docker_registry_domain }}"

    - name: Install utility packages
      apt:
        pkg:
          - net-tools
          - vim
        state: present
        update_cache: yes

  roles:
    - docker
    - docker-registry
    - nginx
    - redis
    # - containers
