---
- hosts: all
  become: true
  become_method: sudo

  pre_tasks:
    - name: Set the system timezone
      timezone:
        name: "{{ server_timezone }}"
    - name: Print the environment configuration
      debug:
        msg: "Launching in mode: {{ 'development' if development_mode else 'production'}}"
    # We will add the user running the playbook to the docker group
    - name: Get the username running the deploy
      become: false
      command: whoami
      register: username_on_the_host_output
    - set_fact:
        ansible_user: "{{ username_on_the_host_output.stdout }}"

  # Additional tasks when running in development mode
  tasks:
    - name: Development mode extra configuration
      block:
        - name: Install utility packages
          apt:
            pkg:
              - net-tools
              - vim
            state: present
            update_cache: yes
        - name: Add ansible user to docker group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes
      when: development_mode

  roles:
    - docker
    - docker-registry
    - nginx
    - redis
    - firewall
    - api
    - runner
    - app

