---
- hosts: all
  become: true
  become_method: sudo
  vars:
    ansible_port: "{{ ssh_port }}"
  vars_files:
    # Configuration parameters
    - configuration/config.yml
    # Secret files
    - secrets/sudo_password.yml
    - secrets/redis_password.yml
    - secrets/registry_users.yml
    - secrets/registry_password.yml

  pre_tasks:
    - name: Set the system timezone
      timezone:
        name: "{{ server_timezone }}"
    - name: Print the environment configuration
      debug:
        msg: "Launching in mode: {{ 'development' if development_mode else 'production'}}"
    # We will add the user running the playbook to the docker group
    - name: Get the username running the deploy
      become: false
      command: whoami
      register: username_on_the_host_output
    - set_fact:
        ansible_user: "{{ username_on_the_host_output.stdout }}"

  # Additional tasks when running in development mode
  tasks:
    - name: Install utility packages
      apt:
        pkg:
          - net-tools
          - vim
        state: present
        update_cache: yes
      when: development_mode and false
    - name: Add ansible user to docker group
      user:
        name=ansible
        groups=docker
        append=yes
      when: development_mode and false

  # Don't needed, dockerode should be able to login to the registry
  # post_tasks:
  #   - name: Log in to Docker registry
  #     docker_login:
  #       registry_url: "https://{{ registry.domain }}"
  #       username: "{{ correctomatic_registry_user }}"
  #       password: "{{ correctomatic_registry_password }}"

  roles:
    - docker
    - docker-registry
    - nginx
    - redis
    - firewall
    - api
    - arunner
