---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - configuration/config.yml
    - secrets/sudo_password.yml
    - secrets/redis_password.yml
    - secrets/registry_users.yml
    - secrets/registry_secret.yml

  pre_tasks:
    - name: Print the environment configuration
      debug:
        msg: "Launching in mode: {{ running_environment }}"
    - name: Print the value of registry domain
      debug:
        msg: "The value of registry domain is {{ registry.domain }}"

  tasks:
    - name: Install utility packages
      apt:
        pkg:
          - net-tools
          - vim
        state: present
        update_cache: yes

  roles:
    - docker
    - docker-registry
    - nginx
    - redis
    # - containers
