---
- hosts: all
  become: true
  become_method: sudo
  vars:
    ansible_port: "{{ ssh_port }}"
  vars_files:
    # Configuration parameters
    - configuration/config.yml
    # Secret files
    - secrets/sudo_password.yml
    - secrets/redis_password.yml
    - secrets/registry_users.yml
    - secrets/registry_password.yml

  pre_tasks:
    - name: Print the environment configuration
      debug:
        msg: "Launching in mode: {{ 'development' if development_mode else 'production'}}"
    - name: Print the value of registry domain
      debug:
        msg: "The value of registry domain is {{ registry.domain }}"
    # We will add the user running the playbook to the docker group
    - name: Get the username running the deploy
      become: false
      command: whoami
      register: username_on_the_host_output
    - set_fact:
        ansible_user: "{{ username_on_the_host_output.stdout }}"

  # Additional tasks when running in development mode
  tasks:
    - name: Install utility packages
      apt:
        pkg:
          - net-tools
          - vim
        state: present
        update_cache: yes
      when: development_mode and false
    - name: Add ansible user to docker group
      user:
        name=ansible
        groups=docker
        append=yes
      when: development_mode and false

  roles:
    - docker
    - docker-registry
    - nginx
    - redis
    - firewall
    - api
    - arunner
