---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - secrets/sudo_password.yml
    - secrets/redis_password.yml
  roles:
    # - docker
    # - nginx
    - redis
    # - containers
