---
- name: Include shared folder creation
  import_tasks: ../../common/tasks/shared_folder.yml

- name: Include correctomatic network creation
  import_tasks: ../../common/tasks/correctomatic_network.yml

- name: Correctomatic API container
  docker_container:
    name: correctomatic-api
    image: "{{ correctomatic.api.image }}:{{ correctomatic.api.tag }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ correctomatic.network.name }}"
    pull: yes
    env:
      PORT: "3000"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_USER: default
      REDIS_PASSWORD: "{{ redis_password }}"
      LOG_LEVEL: "{{ correctomatic.api.log_level }}"
      UPLOAD_DIRECTORY: "{{ correctomatic.shared_folder }}"
    volumes:
      # Exercises' folder
      - "{{ correctomatic.shared_folder }}:{{ correctomatic.shared_folder }}:rw"
    published_ports:
      - "3000:3000"
    # Redis is running on the VPS
    etc_hosts:
      redis: "{{ correctomatic.network.gateway }}"

