---
- name: Include common tasks
  import_tasks: ../../common/tasks/shared_folder.yml

- name: Create correctomatic's Docker network if not present
  docker_network:
    name: "{{ correctomatic.network }}"
    state: present

- name: Run API
  docker_container:
    name: correctomatic-api
    image: "{{ correctomatic.api.image }}:{{ correctomatic.api.tag }}"
    state: started
    pull: yes
    volumes:
      # Shared folder
      - "{{ correctomatic.shared_folder }}:{{ correctomatic.shared_folder }}:rw"
    env:
      PORT=3000
      REDIS_HOST=redis
      REDIS_PORT=6379
      REDIS_USER=default
      REDIS_PASSWORD={{ redis_password }}
      LOG_LEVEL={{ correctomatic.api.log_level }}
      UPLOAD_DIRECTORY={{ correctomatic.shared_folder }}

    published_ports:
      - "3000:3000"
    # Redis is running on the VPS
    etc_hosts:
      redis: host-gateway
    restart_policy: always
