---
- name: Create correctomatic's Docker network if not present
  docker_network:
    name: "{{ correctomatic.network }}"
    # driver: "{{ docker_network_driver }}"
    state: present

- name: Create configurations directory
  file:
    path: /etc/correctomatic/api/
    state: directory
    mode: '0750'

- name: Generate configuration file for the API
  template:
    src: env.j2
    dest: /etc/correctomatic/api/.env
    mode: '0640'

- name: Run API
  docker_container:
    name: correctomatic-api
    image: "{{ correctomatic.api.image }}:{{ correctomatic.api.tag }}"
    state: started
    volumes:
      # Configuration file
      - /etc/correctomatic/api/.env:/app/.env
      # Shared folder
      - "{{ correctomatic.shared_folder }}:{{ correctomatic.shared_folder }}"
    # Redis is running on the host
    etc_hosts:
      redis: host-gateway
    restart_policy: always
