---
- include_tasks: ../../common/tasks/shared_folder.yml

# Cleanup of old exercises and containers, just in case
- include_tasks: delete_old_exercises.yml
- include_tasks: delete_old_containers.yml

- name: Create correctomatic's Docker network if not present
  docker_network:
    name: "{{ correctomatic.network }}"
    state: present

# The docker's secrets are in a folder with restricted access
- include_tasks: prepare_secrets.yml

# Prepare the options for connecting to the Docker daemon
- include_tasks: prepare_docker_options.yml

# The etc_hosts_correctomatic is a dictionary with the hostname as key and the value as the IP
# We need it to pass dynamic etc_hosts entries to the container
- name: Define dynamic etc_hosts entries
  set_fact:
    etc_hosts_correctomatic: >
      {{
        {
          (docker.domain): 'host-gateway',
          'redis': 'host-gateway'
        }
      }}

- name: Add extra hosts to etc_hosts_correctomatic in development
  set_fact:
    etc_hosts_correctomatic: "{{ etc_hosts_correctomatic | combine(correctomatic.notifier.extra_hosts_dev) }}"
  when: development_mode

# Correctomatic processes
- include_tasks: correctomatic_starter.yml
- include_tasks: correctomatic_completer.yml
- include_tasks: correctomatic_notifier.yml
