---
- name: Include shared folder creation
  import_tasks: ../../common/tasks/shared_folder.yml

- name: Include correctomatic network creation
  import_tasks: ../../common/tasks/correctomatic_network.yml

# Cleanup of old exercises and containers, just in case
- include_tasks: delete_old_exercises.yml
- include_tasks: delete_old_containers.yml

# The docker's secrets are in a folder with restricted access
- include_tasks: prepare_secrets.yml

# Prepare the options for connecting to the Docker daemon
- include_tasks: prepare_docker_options.yml

# The etc_hosts_correctomatic is a dictionary with the hostname as key and the value as the IP
# We need it to pass dynamic etc_hosts entries to the container
- name: Define dynamic etc_hosts entries
  set_fact:
    etc_hosts_correctomatic: >
      {{
        {
          (docker.domain): '{{ correctomatic.network.gateway }}',
          'redis': '{{ correctomatic.network.gateway }}',
          'host.docker.internal': '{{ correctomatic.network.gateway }}',
        }
      }}

# host_computer will resolve to the local IP address of the VM's host computer
- block:
  - name: Obtain local IP address
    become: false
    local_action:
      module: shell
      cmd: |
        ip route get $(getent hosts {{ inventory_hostname }} | awk '{ print $1 }') | \
        awk '{ for (x=1;x<=NF;x++) if ($x=="src") print $(x+1) }'
    register: local_address
    changed_when: false

  - name: Add extra hosts to etc_hosts_correctomatic in development
    set_fact:
      etc_hosts_correctomatic: >-
        {{
          etc_hosts_correctomatic |
          combine(
            correctomatic.notifier.extra_hosts_dev
          ) |
          combine(
            {
              'host_computer': local_address.stdout
            }
          )
        }}

  when: development_mode

# Correctomatic processes
- include_tasks: correctomatic_starter.yml
- include_tasks: correctomatic_completer.yml
- include_tasks: correctomatic_notifier.yml
