---
- name: Create the configuration directory
  file:
    path: /correctomatic/app
    state: directory
    mode: '0755'
    owner: root
    group: docker

- name: Create the configuration file
  template:
    src: correctomatic.json.j2
    dest: /correctomatic/app/correctomatic.json

- name: Generate a private key
  community.crypto.openssl_privatekey:
    path: /correctomatic/app/private.key
    type: RSA
    size: 2048

- name: Generate a public key from the private key
  community.crypto.openssl_publickey:
    path: /correctomatic/app/public.key
    privatekey_path: /correctomatic/app/private.key

- name: Change permissions of the private key file to be readable by all
  file:
    path: /correctomatic/app/private.key
    mode: '0644'
