---
- name: Ensure Git is installed
  apt:
    name: git
    state: present
  become: true

- name: Clone the repository
  git:
    repo: 'https://github.com/correctomatic/correctomatic-app.git'
    dest: /tmp/correctomatic-app
    update: yes

- name: Build the Docker image
  docker_image:
    build:
      path: /tmp/correctomatic-app
    name: correctomatic/app
    tag: latest
    source: build
