---
- name: Ensure Git is installed
  apt:
    name: git
    state: present
  become: true

- name: Clone the repository
  git:
    repo: "{{ correctomatic.app.repo }}"
    version: "{{ correctomatic.app.branch }}"
    dest: /tmp/correctomatic-app
    update: yes

- name: Build the Docker image
  docker_image:
    name: correctomatic/app
    tag: latest
    source: build
    build:
      path: /tmp/correctomatic-app
