---
- block:
  - name: Ensure database for Correctomatic App is present
    postgresql_db:
      name: "{{ correctomatic.app.db.name }}"
      encoding: "{{ correctomatic.app.db.encoding }}"
      lc_collate: "{{ correctomatic.app.db.lc_collate }}"
      lc_ctype: "{{ correctomatic.app.db.lc_ctype }}"
      template: template0

  - name: Ensure PostgreSQL role exists
    postgresql_user:
      name: "{{ app_db_user }}"
      password: "{{ app_db_password }}"
      state: present

  - name: Grant all privileges on the database to the user
    postgresql_query:
      db: "{{ correctomatic.app.db.name }}"
      query: "GRANT ALL PRIVILEGES ON DATABASE {{ correctomatic.app.db.name }} TO {{ app_db_user }}"

  # Note: the DB port is closed by default, so we need to open it in the firewall manually when needed
  - name: Allow remote connections for app user
    lineinfile:
      path: "/etc/postgresql/{{ postgresql.version }}/main/pg_hba.conf"
      insertafter: "^#.*TYPE.*DATABASE.*USER.*ADDRESS.*METHOD"
      line: "host    {{ correctomatic.app.db.name }}             {{ app_db_user }}    0.0.0.0/0    scram-sha-256"
    notify: Restart PostgreSQL

  become: true
  become_user: postgres

# TEMP: Builds the Docker image from the repo
- include_tasks: get_image.yml
- include_tasks: generate_configuration.yml

# Starts the Docker container
# - include_tasks: start_container.yml
