---
- block:
  - name: Ensure database for Correctomatic App is present
    postgresql_db:
      name: "{{ correctomatic.app.db.name }}"
      encoding: "{{ correctomatic.app.db.encoding }}"
      lc_collate: "{{ correctomatic.app.db.lc_collate }}"
      lc_ctype: "{{ correctomatic.app.db.lc_ctype }}"
      template: template0

  - name: Ensure PostgreSQL role exists
    postgresql_user:
      name: "{{ app_db_user }}"
      password: "{{ app_db_password }}"
      state: present

  - name: Grant all privileges on the database to the user
    postgresql_query:
      db: "{{ correctomatic.app.db.name }}"
      query: "GRANT ALL PRIVILEGES ON DATABASE {{ correctomatic.app.db.name }} TO {{ app_db_user }}"

  become: true
  become_user: postgres
