---

- name: Create the network for the app container
  docker_network:
    name: "{{ correctomatic.app.network.name }}"
    state: present
    ipam_config:
      - subnet: "{{ correctomatic.app.network.subnet }}"
        gateway: "{{ correctomatic.app.network.gateway }}"

- name: Run correctomatic-app container
  docker_container:
    name: correctomatic-app
    image: correctomatic/app
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ correctomatic.app.network.name }}"
    env:
      PORT: "{{ correctomatic.app.internal_port }}"
      POSTGRES_USER: "{{ app_db_user }}"
      POSTGRES_PASSWORD: "{{ app_db_password }}"
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: '5432'
      POSTGRES_DB: "{{ correctomatic.app.db.name }}"
      CORRECTOMATIC_API_SERVER: http://host.docker.internal:3000
      CALLBACK_HOST: http://host.docker.internal:{{ correctomatic.app.internal_port }}
      UPLOAD_FOLDER: /uploads
      LTI_CONFIG_DIR: /lti_config
      LOG_LEVEL: "{{ correctomatic.app.log_level }}"
    volumes:
      - "{{ correctomatic.app.uploads_dir }}:/uploads:rw"
      - /correctomatic/app/config:/lti_config:rw
    ports:
      - "{{ correctomatic.app.internal_port }}:{{ correctomatic.app.internal_port }}"
    etc_hosts:
      host.docker.internal: host-gateway
      postgres: "{{ correctomatic.app.network.gateway }}"
