---
- name: Run correctomatic-app container
  docker_container:
    name: correctomatic-app
    image: correctomatic/app
    state: started
    restart_policy: no
    env:
      PORT: "{{ correctomatic.app.internal_port }}"
      POSTGRES_USER: "{{ app_db_user }}"
      POSTGRES_PASSWORD: "{{ app_db_password }}"
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: '5432'
      POSTGRES_DB: "{{ correctomatic.app.db.name }}"
      CORRECTOMATIC_API_SERVER: https://host.docker.internal:3000
      CALLBACK_HOST: http://host.docker.internal:{{ correctomatic.app.internal_port }}
      UPLOAD_FOLDER: /uploads
      LTI_CONFIG_DIR: /lti_config
    volumes:
      - /correctomatic/app/uploads:/uploads"
      - /correctomatic/app/config:/lti_config"
    ports:
      - "{{ correctomatic.app.internal_port }}:{{ correctomatic.app.internal_port }}"
    etc_hosts:
      host.docker.internal: host-gateway
      postgres: host-gateway
