- name: Create directory with 700 permissions for certificates
  file:
    path: /correctomatic/certs
    state: directory
    mode: '0700'

- name: Copy CA certificate
  command:
    cmd: cp "{{ correctomatic.runner.docker_certs_folder }}/ca/ca-certificate.pem" /correctomatic/certs/ca.pem

- name: Copy client certificate
  command:
    cmd: cp "{{ correctomatic.runner.docker_certs_folder }}/certs/correctomatic-client-certificate.pem" /correctomatic/certs/cert.pem

- name: Copy private key
  command:
    cmd: cp "{{ correctomatic.runner.docker_certs_folder }}/certs/correctomatic-private-key.pem" /correctomatic/certs/key.pem

- name: Give permissions
  command:
    cmd: chmod 644 /correctomatic/certs/key.pem
