---
- name: Create correctomatic notifier container
  tags: debug
  docker_container:
    name: correctomatic-notifier
    image: "{{ correctomatic.runner.image }}:{{ correctomatic.runner.tag }}"
    state: started
    pull: yes
    env:
      PROCESS: notifier
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_USER: default
      REDIS_PASSWORD: "{{ redis_password }}"
      LOG_LEVEL: "{{ correctomatic.notifier.log_level }}"
    # Should I add some host entries for development?
    etc_hosts: "{{ etc_hosts_dict }}"
    restart_policy: unless-stopped
