---
- include_tasks: ../../common/tasks/shared_folder.yml

- name: Create crontab entry for deleting old exercises
  cron:
    name: "Delete old exercises"
    minute: "0"
    hour: "*"
    job: "find {{ correctomatic.shared_folder }} -type f -mmin +{{ correctomatic.runner.delete_exercises_older_than }} -delete"

- name: Create correctomatic's Docker network if not present
  docker_network:
    name: "{{ correctomatic.network }}"
    state: present

# The docker's certificates are copied in a folder with 700 access
- include_tasks: copy_certificates.yml

- name: Create correctomatic starter container
  tags: debug
  docker_container:
    name: correctomatic-starter
    image: "{{ correctomatic.runner.image }}:{{ correctomatic.runner.tag }}"
    state: started
    pull: yes
    volumes:
      # Exercises' folder
      - "{{ correctomatic.shared_folder }}:{{ correctomatic.shared_folder }}:rw"
      # Certs. Must mount the files because the dir is not readable
      - "/correctomatic/certs/ca.pem:/certs/ca.pem:ro"
      - "/correctomatic/certs/cert.pem:/certs/cert.pem:ro"
      - "/correctomatic/certs/key.pem:/certs/key.pem:ro"
    env:
      PROCESS: starter
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_USER: default
      REDIS_PASSWORD: "{{ redis_password }}"
      LOG_LEVEL: "{{ correctomatic.starter.log_level }}"
      UPLOAD_DIRECTORY: "{{ correctomatic.shared_folder }}"
      DOCKER_OPTIONS: |
        {
          "host": "docker-server",
          "protocol": "https",
          "port": 2376,
          "ca": "/certs/ca.pem",
          "cert": "/certs/cert.pem",
          "key": "/certs/key.pem"
        }
    # Redis is running on the VPS
    etc_hosts:
      redis: host-gateway
      docker-server: host-gateway
    restart_policy: no
    # register: container_creation


