---
- name: Create shared volume directory
  file:
    path: "{{ registry.shared_folder }}"
    state: directory

- name: Crontab for deleting old exercises
  cron:
    name: "Delete exercises older than {{ registry.delete_exercises_older_than }} minutes"
    minute: "0"
    hour: "*"
    job: "find /path/to/directory -type f -mmin +{{ registry.delete_exercises_older_than }} -delete"

- name: Whatever
  notify:
    - Restart Docker

- name: Create Docker network
  docker_network:
    name: custom_network
    state: present

- name: Run custom container 1
  docker_container:
    name: custom_container1
    image: your_custom_image1
    state: started
    networks:
      - name: custom_network
    volumes:
      - /srv/shared:/srv/shared

- name: Run custom container 2
  docker_container:
    name: custom_container2
    image: your_custom_image2
    state: started
    networks:
      - name: custom_network
    volumes:
      - /srv/shared:/srv/shared

- name: Run PostgreSQL container
  docker_container:
    name: postgres_container
    image: postgres
    state: started
    networks:
      - name: custom_network
    volumes:
      - /srv/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: your_password
