---
- include_tasks: ../../common/tasks/shared_folder.yml

# Cleanup of old exercises and containers, just in case
- include_tasks: delete_old_exercises.yml
- include_tasks: delete_old_containers.yml

- name: Create correctomatic's Docker network if not present
  docker_network:
    name: "{{ correctomatic.network }}"
    state: present

# The docker's certificates are copied in a folder with 700 access
- include_tasks: copy_certificates.yml

# Correctomatic processes
- include_tasks: starter.yml
