---
# The etc_hosts_dict is a dictionary with the hostname as key and the value as the IP
# We need it to pass dynamic etc_hosts entries to the container
- name: Define dynamic etc_hosts entries
  set_fact:
    etc_hosts_dict: >
      {{
        {
          (docker.domain): 'host-gateway',
          'redis': 'host-gateway'
        }
      }}

- name: Create correctomatic starter container
  tags: debug
  docker_container:
    name: correctomatic-starter
    image: "{{ correctomatic.runner.image }}:{{ correctomatic.runner.tag }}"
    state: started
    pull: yes
    volumes:
      # Exercises' folder
      - "{{ correctomatic.shared_folder }}:{{ correctomatic.shared_folder }}:rw"
      # Certs. Must mount the files because the dir is not readable
      - "/correctomatic/secrets/certs/ca.pem:/certs/ca.pem:ro"
      - "/correctomatic/secrets/certs/cert.pem:/certs/cert.pem:ro"
      - "/correctomatic/secrets/certs/key.pem:/certs/key.pem:ro"
      # Registry credentials
      - "/correctomatic/secrets/registry_credentials.json:/run/registry_credentials.json:ro"
    env:
      PROCESS: starter
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_USER: default
      REDIS_PASSWORD: "{{ redis_password }}"
      LOG_LEVEL: "{{ correctomatic.starter.log_level }}"
      UPLOAD_DIRECTORY: "{{ correctomatic.shared_folder }}"
      DOCKER_TIMEOUT: "{{ correctomatic.docker_timeout }}"
      # We need to use to_json to convert the dictionary to a string
      DOCKER_OPTIONS: |
        {{
          {
            "host": docker.domain,
            "protocol": "https",
            "port": 2376,
            "ca": "/certs/ca.pem",
            "cert": "/certs/cert.pem",
            "key": "/certs/key.pem"
          } | to_json
        }}
      DOCKER_PULL: "true"
      DOCKER_REGISTRY_CREDENTIALS_FILE: "/run/registry_credentials.json"
    etc_hosts: "{{ etc_hosts_dict }}"
    restart_policy: unless-stopped


