- name: Ensure directories for storing certificates exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - /etc/docker/certs
    - /etc/docker/ca

# -------------------------------
# Certificate authority
# -------------------------------
- name: Create CA private key
  openssl_privatekey:
    path: "{{ docker_ca.private_key }}"

- name: Create CSR for CA certificate
  community.crypto.openssl_csr:
    path: /etc/docker/ca/ca.csr
    privatekey_path: "{{ docker_ca.private_key }}"
    common_name: Docker CA
    use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ docker_ca.certificate }}"
    csr_path: /etc/docker/ca/ca.csr
    privatekey_path: "{{ docker_ca.private_key }}"
    provider: selfsigned

# -------------------------------
# Server
# -------------------------------
- name: Generate server private key
  openssl_privatekey:
    path: "{{ docker_server.private_key }}"
    size: 4096
    state: present

- name: Generate server certificate signing request (CSR)
  openssl_csr:
    path: /etc/docker/certs/docker-server.csr
    privatekey_path: "{{ docker_server.private_key }}"
    common_name: "{{ docker.domain }}"
    subject_alt_name:
      - "DNS:{{ docker.domain }}"
    key_usage:
      - digitalSignature
    key_usage_critical: true
    extended_key_usage:
      - serverAuth
      - clientAuth
    extended_key_usage_critical: yes

- name: Sign server certificate with the CA
  openssl_certificate:
    path: "{{ docker_server.certificate }}"
    csr_path: /etc/docker/certs/docker-server.csr
    ownca_privatekey_path: "{{ docker_ca.private_key }}"
    ownca_path: "{{ docker_ca.certificate }}"
    provider: ownca

# -------------------------------
# Client
# -------------------------------
- name: Generate client private key
  openssl_privatekey:
    path: "{{ docker_client.private_key }}"
    size: 4096

- name: Generate client certificate signing request (CSR)
  openssl_csr:
    path: /etc/docker/certs/correctomatic-client.csr
    privatekey_path: "{{ docker_client.private_key }}"
    common_name: "Correctomatic client"
    key_usage:
      - digitalSignature
    key_usage_critical: true
    extended_key_usage:
      - clientAuth

- name: Sign client certificate with the CA
  openssl_certificate:
    path: "{{ docker_client.certificate }}"
    csr_path: /etc/docker/certs/correctomatic-client.csr
    ownca_privatekey_path: "{{ docker_ca.private_key }}"
    ownca_path: "{{ docker_ca.certificate }}"
    provider: ownca
