---
- include_tasks: generate_certificates.yml

# The systemd unit file comes with the hosts' configuration, and we want to configure everything in daemon.json
# If we configure the hosts in both places, we get an error
- name: Ensure directory for systemd overrides exists
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Overrides host configuration for systemd
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
  notify:
    - Restart Docker

- name: Copy Docker daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - Restart Docker

# /usr/lib/systemd/system/docker.service
# They don't seem to consider this a bug. But it is definitely an annoyance. A workaround is to copy the default unit file and remove the -H fd:// from it:

# $ sudo cp /lib/systemd/system/docker.service /etc/systemd/system/
# $ sudo sed -i 's/\ -H\ fd:\/\///g' /etc/systemd/system/docker.service
# $ sudo systemctl daemon-reload
# $ sudo systemctl restart docker

# For systemd, my preferred method is to deploy a simple override file (you may need to first create the directory):

# $ cat /etc/systemd/system/docker.service.d/override.conf
# # Disable flags to dockerd, all settings are done in /etc/docker/daemon.json
# [Service]
# ExecStart=
# ExecStart=/usr/bin/dockerd
