- name: Ensure directories for storing certificates exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - /etc/docker/certs
    - /etc/docker/ca


# https://docs.ansible.com/ansible/latest/collections/community/crypto/docsite/guide_ownca.html

# -------------------------------
# Certificate authority
# -------------------------------

- name: Check if CA certificate exists
  stat:
    path: /path/to/your/file
  register: file_check

- name: Create CA private key
  openssl_privatekey:
    path: /etc/docker/ca/ca-private.key
    # passphrase: "{{ secret_ca_passphrase }}"

- name: Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: /etc/docker/ca/ca-private.key
    # privatekey_passphrase: "{{ secret_ca_passphrase }}"
    common_name: Docker CA
    use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr

# Delete csr?

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: /etc/docker/ca/ca-certificate.pem
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: /etc/docker/ca/ca-private.key
    # privatekey_passphrase: "{{ secret_ca_passphrase }}"
    provider: selfsigned


# - name: Generate CA private key
#   openssl_privatekey:
#     path: /etc/docker/ca/ca-private-key.pem
#     size: 4096
#     # passphrase: "your_passphrase_here"
#   register: ca_privatekey

# - name: Generate CA public key
#   openssl_certificate:
#     common_name: "Docker CA"
#     path: /etc/docker/ca/ca-public-key.pem
#     privatekey_path: /etc/docker/ca/ca-private-key.pem
#     # privatekey_passphrase: "your_passphrase_here"
#     provider: selfsigned
#     days: 365

# -------------------------------
# Server
# -------------------------------



- name: Generate server private key
  openssl_privatekey:
    path: /etc/docker/certs/server-private-key.pem
    size: 4096
    state: present
  # register: server_privatekey

- name: Generate server certificate signing request (CSR)
  openssl_csr:
    common_name: "{{ docker.domain }}"
    path: /etc/docker/certs/server.csr
    privatekey_path: /etc/docker/certs/server-private-key.pem
    backup: true
    # creates: /etc/docker/certs/server-cert.pem

# Possible improvement
# - name: Create certificate signing request (CSR) for self-signed certificate
#   community.crypto.openssl_csr_pipe:
#     privatekey_path: /path/to/certificate.key
#     common_name: ansible.com
#     organization_name: Ansible, Inc.
#     subject_alt_name:
#       - "DNS:ansible.com"
#       - "DNS:www.ansible.com"
#       - "DNS:docs.ansible.com"
#   register: csr

- name: Sign server certificate with the CA
  openssl_certificate:
    path: /etc/docker/certs/server-cert.pem
    csr_path: /etc/docker/certs/server.csr
    privatekey_path: /etc/docker/ca/ca-private-key.pem
    # privatekey_passphrase: "your_passphrase_here"
    ca_path: /etc/docker/ca/ca-public-key.pem
    provider: selfsigned
    extended_key_usage: clientAuth,serverAuth
    subject_alt_name:
      - "DNS:{{ docker.domain }}"
    days: 365

# Delete server csr?

# -------------------------------
# Client
# -------------------------------
- name: Generate client private key
  openssl_privatekey:
    path: /etc/docker/certs/key.pem
    size: 4096
  register: client_privatekey

- name: Generate client certificate signing request (CSR)
  openssl_csr:
    common_name: "client"
    path: /etc/docker/certs/client.csr
    privatekey_path: /etc/docker/certs/key.pem

- name: Sign client certificate with the CA
  openssl_certificate:
    path: /etc/docker/certs/cert.pem
    csr_path: /etc/docker/certs/client.csr
    privatekey_path: /etc/docker/ca/ca-private-key.pem
    # privatekey_passphrase: "your_passphrase_here"
    ca_path: /etc/docker/ca/ca-public-key.pem
    provider: selfsigned
    extended_key_usage: clientAuth
    days: 365

# Delete client csr?

# -------------------------------
# Permissions
# -------------------------------
- name: Set permissions for certificates and CA directories
  file:
    path: "{{ item }}"
    # mode: '0700'
    # BIG DEBUG
    mode: '755'
    recurse: yes
  loop:
    - /etc/docker/certs
    - /etc/docker/ca
