---
# - name: Pull Docker registry image
#   docker_image:
#     name: registry
#     tag: latest

- name: Pull the registry image
  docker_image:
    name: registry:latest
    source: pull
    pull:
      platform: amd64

- name: Create the data directory
  

- name: Start Docker registry container
  docker_container:
    name: docker_registry
    image: registry:latest
    ports:
      - "{{ docker_registry_port }}:5000"
    restart_policy: always
    env:
      AUTH_HTPASSWD_REALM: Correctomatic Registry
      AUTH_HTPASSWD_PATH: "{{ htpasswd_file}}"
