# Some task can't be executed in a dev environment, ie, certbot, and we will need
# some additional tasks (open ports, etc.)
development_mode: yes

# Change if you have a non-standard ssh port
ssh_port: 22

registry:
  domain: "registry.correctomatic.alvaromaceda.es"
  data_directory: "/var/registry"
  internal_port: 5000

docker:
  domain: "docker.correctomatic.alvaromaceda.es"

runner:
  shared_folder: /exercises/shared
  # minutes
  delete_exercises_older_than: 60

# correctomatic_app_domain: "correctomatic.alvaromaceda.es"
lets_encrypt_email: "alvaro@alvaromaceda.es"

# DEBUG, should be protected in production
correctomatic_api_domain: "api.correctomatic.alvaromaceda.es"
