# Some task can't be executed in a dev environment, ie, certbot
running_environment: "development"

# domains:
#   api: foo
#   registry: foo

registry_domain: "registry.correctomatic.alvaromaceda.es"
correctomatic_app_domain: "correctomatic.alvaromaceda.es"
lets_encrypt_email: "alvaro@alvaromaceda.es"

# DEBUG, should be protected in production
correctomatic_api_domain: "api.correctomatic.alvaromaceda.es"
